[import]
filename = "/Users/jonathan/Downloads/AARCHMRS_OPENSOURCE_A_profile_FAT-2025-12/Registers.json"

[generate.registers.ACTLR]

[generate.registers.ACTLR2]

[generate.registers.ADFSR]

[generate.registers.AIDR]

[generate.registers.AIFSR]

[generate.registers.AMAIR0]

[generate.registers.AMAIR1]

[generate.registers.BPIALL]

[generate.registers.CCSIDR]

[generate.registers.CLIDR]

[generate.registers.CONTEXTIDR]

[generate.registers.CPACR]

[generate.registers.CPSR]

[generate.registers.CSSELR]

[generate.registers.CTR]

[generate.registers.DACR]

[generate.registers.DC_SW_OPS]

[generate.registers.DCCIMVAC]

[generate.registers.DCCISW]

[generate.registers.DCCMVAC]

[generate.registers.DCCMVAU]

[generate.registers.DCCSW]

[generate.registers.DCIMVAC]

[generate.registers.DCISW]

[generate.registers.DFAR]

[generate.registers.DFSR]

[[generate.registers.DFSR.rename]]
from = "m[4:0]"
to = "m"

[generate.registers.DLR]

[generate.registers.DRACR]

[generate.registers.DRBAR]

[generate.registers.DRSR]

[generate.registers.DSPSR]

[[generate.registers.DSPSR.rename]]
from = "m[4:0]"
to = "m"

[generate.registers.FCSEIDR]

[generate.registers.ICC_PMR]

[generate.registers.ICIALLU]

[generate.registers.ID_AFR0]

[generate.registers.ID_DFR0]

[generate.registers.ID_ISAR0]

[generate.registers.ID_ISAR1]

[generate.registers.ID_ISAR2]

[generate.registers.ID_ISAR3]

[generate.registers.ID_ISAR4]

[generate.registers.ID_ISAR5]

[generate.registers.ID_MMFR0]

[generate.registers.ID_MMFR1]

[generate.registers.ID_MMFR2]

[generate.registers.ID_MMFR3]

[generate.registers.ID_MMFR4]

[generate.registers.ID_PFR0]

[generate.registers.ID_PFR1]

[generate.registers.IFAR]

[generate.registers.IFSR]

[generate.registers.IMP]

[generate.registers.IRACR]

[generate.registers.IRBAR]

[generate.registers.IRSR]

[generate.registers.MAIR0]

[generate.registers.MAIR1]

[generate.registers.MIDR]

[generate.registers.MPIDR]
description = "Multiprocessor Affinity Register"

[generate.registers.MPUIR]

[generate.registers.NSACR]

[generate.registers.PAR]
fieldset = 1

[[generate.registers.PAR.rename]]
from = "fs[5]"
to = "fs5"

[[generate.registers.PAR.rename]]
from = "fs[4:0]"
to = "fs"

[generate.registers.PMCCFILTR]

[generate.registers.PMCCNTR]

[generate.registers.PMCEID0]

[generate.registers.PMCEID1]

[generate.registers.PMCNTENCLR]

[generate.registers.PMCNTENSET]

[generate.registers.PMCR]

[generate.registers.PMEVCNTR0]

[generate.registers.PMEVCNTR1]

[generate.registers.PMEVCNTR2]

[generate.registers.PMEVCNTR3]

[generate.registers.PMEVTYPER0]

[[generate.registers.PMEVTYPER0.rename]]
from = "evtcount[9:0]"
to = "evtcount"

[generate.registers.PMEVTYPER1]

[[generate.registers.PMEVTYPER1.rename]]
from = "evtcount[9:0]"
to = "evtcount"

[generate.registers.PMEVTYPER2]

[[generate.registers.PMEVTYPER2.rename]]
from = "evtcount[9:0]"
to = "evtcount"

[generate.registers.PMEVTYPER3]

[[generate.registers.PMEVTYPER3.rename]]
from = "evtcount[9:0]"
to = "evtcount"

[generate.registers.PMINTENCLR]

[generate.registers.PMINTENSET]

[generate.registers.PMOVSR]

[generate.registers.PMOVSSET]

[generate.registers.PMSELR]

[generate.registers.PMSWINC]

[generate.registers.PMUSERENR]

[generate.registers.PMXEVCNTR]

[[generate.registers.PMXEVCNTR.rename]]
from = "pmevcntr<n>"
to = "pmevcntr_n"

[generate.registers.PMXEVTYPER]

[generate.registers.REVIDR]

[generate.registers.RGNR]

[generate.registers.RVBAR]

[generate.registers.SCTLR]

[generate.registers.TCMTR]

[generate.registers.TLBIALL]

[generate.registers.TLBTR]

[generate.registers.TPIDRPRW]

[generate.registers.TPIDRURO]

[generate.registers.TPIDRURW]

[generate.registers.TTBR0]

[generate.registers.VMPIDR]

[generate.registers.VPIDR]

[generate.registers.VSCTLR]

[generate.registers.CNTFRQ]

[generate.registers.CNTHCTL]

[generate.registers.CNTHP_CTL]

[generate.registers.CNTHP_CVAL]

[generate.registers.CNTHP_TVAL]

[generate.registers.CNTKCTL]

[generate.registers.CNTP_CTL]

[generate.registers.CNTP_CVAL]

[generate.registers.CNTP_TVAL]

[generate.registers.CNTPCT]

[generate.registers.CNTV_CTL]

[generate.registers.CNTV_CVAL]

[generate.registers.CNTV_TVAL]

[generate.registers.Cnt_vct]

[generate.registers.CNTVOFF]

[generate.registers.HACR]

[generate.registers.HACTLR]

[generate.registers.HACTLR2]

[generate.registers.HADFSR]

[generate.registers.HAIFSR]

[generate.registers.HAMAIR0]

[generate.registers.HAMAIR1]

[generate.registers.HCPTR]

[generate.registers.HCR]

[generate.registers.HCR2]

[generate.registers.HDCR]

[generate.registers.HDFAR]

[generate.registers.HIFAR]

[generate.registers.HMAIR0]

[generate.registers.HMAIR1]

[generate.registers.HMPUIR]

[generate.registers.HPFAR]

[[generate.registers.HPFAR.rename]]
from = "fipa[39:12]"
to = "fipa"

[generate.registers.HPRBAR]

[generate.registers.HPRBAR0]

[generate.registers.HPRBAR1]

[generate.registers.HPRBAR10]

[generate.registers.HPRBAR11]

[generate.registers.HPRBAR12]

[generate.registers.HPRBAR13]

[generate.registers.HPRBAR14]

[generate.registers.HPRBAR15]

[generate.registers.HPRBAR2]

[generate.registers.HPRBAR3]

[generate.registers.HPRBAR4]

[generate.registers.HPRBAR5]

[generate.registers.HPRBAR6]

[generate.registers.HPRBAR7]

[generate.registers.HPRBAR8]

[generate.registers.HPRBAR9]

[generate.registers.HPRENR]

[generate.registers.HPRLAR]

[generate.registers.HPRLAR0]

[generate.registers.HPRLAR1]

[generate.registers.HPRLAR10]

[generate.registers.HPRLAR11]

[generate.registers.HPRLAR12]

[generate.registers.HPRLAR13]

[generate.registers.HPRLAR14]

[generate.registers.HPRLAR15]

[generate.registers.HPRLAR2]

[generate.registers.HPRLAR3]

[generate.registers.HPRLAR4]

[generate.registers.HPRLAR5]

[generate.registers.HPRLAR6]

[generate.registers.HPRLAR7]

[generate.registers.HPRLAR8]

[generate.registers.HPRLAR9]

[generate.registers.HPRSELR]

[generate.registers.HSCTLR]

[generate.registers.HSR]

[generate.registers.HSTR]

[generate.registers.HTPIDR]

[generate.registers.HVBAR]

[generate.registers.PRBAR]

[generate.registers.PRBAR0]

[generate.registers.PRBAR1]

[generate.registers.PRBAR10]

[generate.registers.PRBAR11]

[generate.registers.PRBAR12]

[generate.registers.PRBAR13]

[generate.registers.PRBAR14]

[generate.registers.PRBAR15]

[generate.registers.PRBAR2]

[generate.registers.PRBAR3]

[generate.registers.PRBAR4]

[generate.registers.PRBAR5]

[generate.registers.PRBAR6]

[generate.registers.PRBAR7]

[generate.registers.PRBAR8]

[generate.registers.PRBAR9]

[generate.registers.PRLAR]

[generate.registers.PRLAR0]

[generate.registers.PRLAR1]

[generate.registers.PRLAR10]

[generate.registers.PRLAR11]

[generate.registers.PRLAR12]

[generate.registers.PRLAR13]

[generate.registers.PRLAR14]

[generate.registers.PRLAR15]

[generate.registers.PRLAR2]

[generate.registers.PRLAR3]

[generate.registers.PRLAR4]

[generate.registers.PRLAR5]

[generate.registers.PRLAR6]

[generate.registers.PRLAR7]

[generate.registers.PRLAR8]

[generate.registers.PRLAR9]

[generate.registers.PRSELR]

[generate.registers.VBAR]

[export]
folder = "../aarch32-cpu/src/register/autogen"
